### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './inverse_renderer.py'

### ISSUE THREAD

**Issue by YuhsiHu** [Kai-46/IRON#5]
Thank you for your sharing!
I clone your repo and download the dataset. When I run 

> bash train_scene.sh dataset/luan/buddha

There is an error because we do not have inverse_render.py. Besides, there is an AssertionError.

> Hello Wooden 
Load data: Begin
Not using masks
image shape, mask shape:  torch.Size([80, 768, 1024, 3]) torch.Size([80, 768, 1024, 3])
image pixel range:  0.0 1.0
Load data: End
  0%|                                                | 0/100001 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "render_volume.py", line 449, in <module>
    runner.train()
  File "render_volume.py", line 156, in train
    self.optimizer.step()
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/optim/optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/optim/adam.py", line 157, in step
    adam(params_with_grad,
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/optim/adam.py", line 213, in adam
    func(params,
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/optim/adam.py", line 255, in _single_tensor_adam
    assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
AssertionError: If capturable=False, state_steps should not be CUDA tensors.
ic| args: Namespace(data_dir='./dataset/dataset/luan/buddha/train', eik_weight=0.1, export_all=False, gamma_pred=True, init_light_scale=8.0, inv_gamma_gt=False, is_metal=False, neus_ckpt_fpath='./exp_iron_stage1/dataset/luan/buddha/checkpoints/ckpt_100000.pth', no_edgesample=False, num_iters=50001, out_dir='./exp_iron_stage2/dataset/luan/buddha', patch_size=128, plot_image_name=None, render_all=False, roughrange_weight=0.1, ssim_weight=1.0)
Wrote config file to ./exp_iron_stage2/dataset/luan/buddha/args.txt
Traceback (most recent call last):
  File "render_surface.py", line 73, in <module>
    shutil.copy2("./inverse_renderer.py", os.path.join(args.out_dir, "code/inverse_renderer.py"))
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: './inverse_renderer.py'
ic| args: Namespace(data_dir='./dataset/dataset/luan/buddha/test', eik_weight=0.1, export_all=False, gamma_pred=True, init_light_scale=8.0, inv_gamma_gt=False, is_metal=False, neus_ckpt_fpath='./exp_iron_stage1/dataset/luan/buddha/checkpoints/ckpt_100000.pth', no_edgesample=False, num_iters=50001, out_dir='./exp_iron_stage2/dataset/luan/buddha', patch_size=128, plot_image_name=None, render_all=True, roughrange_weight=0.1, ssim_weight=1.0)
Wrote config file to ./exp_iron_stage2/dataset/luan/buddha/args.txt
Traceback (most recent call last):
  File "render_surface.py", line 73, in <module>
    shutil.copy2("./inverse_renderer.py", os.path.join(args.out_dir, "code/inverse_renderer.py"))
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: './inverse_renderer.py'

Could you please fix these bugs? Thank you for your time!

**Comment by endlesswho** [comment]
> Thank you for your sharing! I clone your repo and download the dataset. When I run
> 
> > bash train_scene.sh dataset/luan/buddha
> 
> There is an error because we do not have inverse_render.py. Besides, there is an AssertionError.
> 
> > Hello Wooden
> > Load data: Begin
> > Not using masks
> > image shape, mask shape:  torch.Size([80, 768, 1024, 3]) torch.Size([80, 768, 1024, 3])
> > image pixel range:  0.0 1.0
> > Load data: End
> > 0%|                                                | 0/100001 [00:00<?, ?it/s]
> > Traceback (most recent call last):
> > File "render_volume.py", line 449, in 
> > runner.train()
> > File "render_volume.py", line 156, in train
> > self.optimizer.step()
> > File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/optim/optimizer.py", line 109, in wrapper
> > return func(*args, **kwargs)
> > File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
> > return func(*args, **kwargs)
> > File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/optim/adam.py", line 157, in step
> > adam(params_with_grad,
> > File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/optim/adam.py", line 213, in adam
> > func(params,
> > File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/optim/adam.py", line 255, in _single_tensor_adam
> > assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
> > AssertionError: If capturable=False, state_steps should not be CUDA tensors.
> > ic| args: Namespace(data_dir='./dataset/dataset/luan/buddha/train', eik_weight=0.1, export_all=False, gamma_pred=True, init_light_scale=8.0, inv_gamma_gt=False, is_metal=False, neus_ckpt_fpath='./exp_iron_stage1/dataset/luan/buddha/checkpoints/ckpt_100000.pth', no_edgesample=False, num_iters=50001, out_dir='./exp_iron_stage2/dataset/luan/buddha', patch_size=128, plot_image_name=None, render_all=False, roughrange_weight=0.1, ssim_weight=1.0)
> > Wrote config file to ./exp_iron_stage2/dataset/luan/buddha/args.txt
> > Traceback (most recent call last):
> > File "render_surface.py", line 73, in 
> > shutil.copy2("./inverse_renderer.py", os.path.join(args.out_dir, "code/inverse_renderer.py"))
> > File "/home/hyx/anaconda3/envs/iron/lib/python3.8/shutil.py", line 435, in copy2
> > copyfile(src, dst, follow_symlinks=follow_symlinks)
> > File "/home/hyx/anaconda3/envs/iron/lib/python3.8/shutil.py", line 264, in copyfile
> > with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> > FileNotFoundError: [Errno 2] No such file or directory: './inverse_renderer.py'
> > ic| args: Namespace(data_dir='./dataset/dataset/luan/buddha/test', eik_weight=0.1, export_all=False, gamma_pred=True, init_light_scale=8.0, inv_gamma_gt=False, is_metal=False, neus_ckpt_fpath='./exp_iron_stage1/dataset/luan/buddha/checkpoints/ckpt_100000.pth', no_edgesample=False, num_iters=50001, out_dir='./exp_iron_stage2/dataset/luan/buddha', patch_size=128, plot_image_name=None, render_all=True, roughrange_weight=0.1, ssim_weight=1.0)
> > Wrote config file to ./exp_iron_stage2/dataset/luan/buddha/args.txt
> > Traceback (most recent call last):
> > File "render_surface.py", line 73, in 
> > shutil.copy2("./inverse_renderer.py", os.path.join(args.out_dir, "code/inverse_renderer.py"))
> > File "/home/hyx/anaconda3/envs/iron/lib/python3.8/shutil.py", line 435, in copy2
> > copyfile(src, dst, follow_symlinks=follow_symlinks)
> > File "/home/hyx/anaconda3/envs/iron/lib/python3.8/shutil.py", line 264, in copyfile
> > with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> > FileNotFoundError: [Errno 2] No such file or directory: './inverse_renderer.py'
> 
> Could you please fix these bugs? Thank you for your time!

It seems inverse_renderer.py is useless, I comment the code and  everything seems ok.

**Comment by YuhsiHu** [comment]
Thank you for informing me. I can train now but there is a OOM when render_surface: 

> RuntimeError: CUDA out of memory. Tried to allocate 196.00 MiB (GPU 0; 11.76 GiB total capacity; 6.94 GiB already allocated; 211.00 MiB free; 9.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

My GPU is 3060 (12G). Is it possibile to change any param to run?

**Comment by YuhsiHu** [comment]
The whole log is: 

> ic| args: Namespace(data_dir='./data_flashlight/luan/buddha/test', eik_weight=0.1, export_all=False, gamma_pred=True, init_light_scale=8.0, inv_gamma_gt=False, is_metal=False, neus_ckpt_fpath='./exp_iron_stage1/luan/buddha/checkpoints/ckpt_100000.pth', no_edgesample=False, num_iters=50001, out_dir='./exp_iron_stage2/luan/buddha', patch_size=128, plot_image_name=None, render_all=True, roughrange_weight=0.1, ssim_weight=1.0)
Wrote config file to ./exp_iron_stage2/luan/buddha/args.txt
render_surface.py:257: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning dissapear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  im = imageio.imread(fpath).astype(np.float32) / 255.0
ic| len(image_fpaths): 20
    gt_images.shape: torch.Size([20, 768, 1024, 3])
    Ks.shape: torch.Size([20, 4, 4])
    W2Cs.shape: torch.Size([20, 4, 4])
    len(cameras): 20
ic| args.neus_ckpt_fpath: './exp_iron_stage1/luan/buddha/checkpoints/ckpt_100000.pth'
ic| "Reloading from checkpoint: ": 'Reloading from checkpoint: '
    ckpt_fpath: './exp_iron_stage2/luan/buddha/ckpt_50000.pth'
ic| dist: 1.0408688187599182
    color_network_dict["point_light_network"].light.data: tensor(5.4597, device='cuda:0')
ic| start_step: 50000
ic| f"Rendering images to: {render_out_dir}": 'Rendering images to: ./exp_iron_stage2/luan/buddha/render_test_50000'
  5%|██▏                                         | 1/20 [00:12<03:53, 12.27s/it]
Traceback (most recent call last):
  File "render_surface.py", line 368, in <module>
    results = render_camera(
  File "/home/hyx/iron/models/raytracer.py", line 834, in render_camera
    results = raytrace_camera(
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/hyx/iron/models/raytracer.py", line 581, in raytrace_camera
    results = raytrace_pixels(sdf_network, raytracer, camera.get_uv(), camera, max_num_rays=max_num_rays)
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/hyx/iron/models/raytracer.py", line 392, in raytrace_pixels
    results = raytracer(
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/hyx/iron/models/raytracer.py", line 67, in forward
    (sampler_convergent_mask, sampler_points, sampler_sdf, sampler_dis,) = self.ray_sampler(
  File "/home/hyx/iron/models/raytracer.py", line 154, in ray_sampler
    sdf_val.append(sdf(pnts))
  File "/home/hyx/iron/models/raytracer.py", line 370, in <lambda>
    sdf = lambda x: sdf_network(x)[..., 0]
  File "/home/hyx/anaconda3/envs/iron/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hyx/iron/models/fields.py", line 92, in forward
    x = torch.cat([x, inputs], -1) / np.sqrt(2)
RuntimeError: CUDA out of memory. Tried to allocate 196.00 MiB (GPU 0; 11.76 GiB total capacity; 6.94 GiB already allocated; 226.75 MiB free; 9.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Kai-46** [comment]
Maybe try reducing the patch size: https://github.com/Kai-46/IRON/blob/dc56c0865bfb4759a915e97585a13adb26ec7c3e/render_surface.py#L29 ?

**Comment by YuhsiHu** [comment]
Well, I cannot run render_surface.py even if I set patch_size=1. It is weird because I do obtain the first rendered image(you can see 5% in tqdm) and then the OOM error occurs.

> RuntimeError: CUDA out of memory. Tried to allocate 196.00 MiB (GPU 0; 11.76 GiB total capacity; 6.75 GiB already allocated; 236.62 MiB free; 9.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Kai-46** [comment]
This might have something to do with your system configurations. Sorry but I'm not able to judge what goes wrong based on this limited information. Maybe you could try spending some time debugging the issues?

**Comment by Kai-46** [comment]
Closing this issue temporarily.
